from django.db import models
class ImportBatch(models.Model):
 source_package=models.CharField(max_length=255); package_sha256=models.CharField(max_length=64); started_at=models.DateTimeField(auto_now_add=True); completed_at=models.DateTimeField(null=True); status=models.CharField(max_length=20,default='RUNNING'); summary=models.JSONField(default=dict)
class SourceFile(models.Model):
 batch=models.ForeignKey(ImportBatch,on_delete=models.PROTECT,related_name='files'); filename=models.CharField(max_length=255); sha256=models.CharField(max_length=64); byte_size=models.PositiveBigIntegerField()
 class Meta: constraints=[models.UniqueConstraint(fields=['batch','filename'],name='uniq_batch_source')]
class CanonicalField(models.Model):
 class Mapping(models.TextChoices): MAPPED='MAPPED'; DERIVED='DERIVED'; REFERENCE_ONLY='REFERENCE_ONLY'; DEPRECATED='DEPRECATED'; UNRESOLVED='UNRESOLVED'
 key=models.SlugField(max_length=120,unique=True); persian_label=models.CharField(max_length=255); aliases=models.JSONField(default=list); data_type=models.CharField(max_length=30); domain=models.CharField(max_length=60); entity=models.CharField(max_length=60); meaning=models.TextField(); authority=models.CharField(max_length=255); precedence=models.PositiveSmallIntegerField(default=1); nullable=models.BooleanField(default=True); required=models.BooleanField(default=False); searchable=models.BooleanField(default=False); filterable=models.BooleanField(default=False); sortable=models.BooleanField(default=False); exportable=models.BooleanField(default=True); default_visible=models.BooleanField(default=False); sensitive=models.BooleanField(default=False); deprecated=models.BooleanField(default=False); validation_rules=models.JSONField(default=dict); mapping_status=models.CharField(max_length=20,choices=Mapping.choices)
class RawCell(models.Model):
 source_file=models.ForeignKey(SourceFile,on_delete=models.PROTECT); sheet=models.CharField(max_length=255); row_number=models.PositiveIntegerField(); column_number=models.PositiveIntegerField(); original_heading=models.CharField(max_length=255); raw_value=models.TextField(blank=True); value_type=models.CharField(max_length=30); row_fingerprint=models.CharField(max_length=64); field=models.ForeignKey(CanonicalField,on_delete=models.PROTECT,null=True); mapping_status=models.CharField(max_length=20,choices=CanonicalField.Mapping.choices); imported_at=models.DateTimeField(auto_now_add=True)
 class Meta: indexes=[models.Index(fields=['source_file','sheet','row_number'])]; constraints=[models.UniqueConstraint(fields=['source_file','sheet','row_number','column_number'],name='uniq_raw_cell')]
class Discrepancy(models.Model):
 class Status(models.TextChoices): OPEN='OPEN','باز'; REVIEWING='REVIEWING','در بررسی'; RESOLVED='RESOLVED','حل‌شده'
 source_file=models.ForeignKey(SourceFile,on_delete=models.PROTECT,null=True); entity_type=models.CharField(max_length=80); entity_key=models.CharField(max_length=120); field_key=models.CharField(max_length=120,blank=True); observed_value=models.TextField(blank=True); expected_value=models.TextField(blank=True); reason=models.TextField(); severity=models.CharField(max_length=20,default='MEDIUM'); status=models.CharField(max_length=20,choices=Status.choices,default=Status.OPEN); assigned_to=models.ForeignKey('auth.User',null=True,blank=True,on_delete=models.SET_NULL); resolution=models.TextField(blank=True); created_at=models.DateTimeField(auto_now_add=True)
