# Generated by Django 5.2.7 on 2026-09-30 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_special", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="CommercialSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=30, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "فعال"), ("OUT_OF_CYCLE", "خارج از چرخه")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("organizational_scope", models.CharField(blank=True, max_length=120)),
                ("asset_type", models.CharField(blank=True, max_length=120)),
                (
                    "area",
                    models.DecimalField(decimal_places=2, max_digits=16, null=True),
                ),
                ("address", models.TextField(blank=True)),
                ("physical_details", models.TextField(blank=True)),
                ("current_usage", models.CharField(blank=True, max_length=255)),
                ("proposed_activity", models.CharField(blank=True, max_length=255)),
                ("activity_group", models.CharField(blank=True, max_length=255)),
                ("previous_usage", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("source_row", models.PositiveIntegerField()),
                ("source_classification", models.CharField(max_length=30)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="properties.center",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="properties.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommercialSpaceStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_state", models.CharField(blank=True, max_length=20)),
                ("new_state", models.CharField(max_length=20)),
                ("effective_date", models.CharField(max_length=10)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "responsible_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.document",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.sourcefile",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_history",
                        to="properties.commercialspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MotherProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("center_type", models.CharField(blank=True, max_length=120)),
                ("primary_usage", models.CharField(blank=True, max_length=120)),
                ("usage_group", models.CharField(blank=True, max_length=120)),
                (
                    "area",
                    models.DecimalField(decimal_places=2, max_digits=16, null=True),
                ),
                ("address", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("source_row", models.PositiveIntegerField()),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="properties.region",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="center",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.region",
            ),
        ),
        migrations.CreateModel(
            name="MotherPropertySpaceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evidence", models.TextField()),
                ("source_sheet", models.CharField(max_length=255)),
                ("source_row", models.PositiveIntegerField()),
                ("confirmed", models.BooleanField(default=True)),
                (
                    "mother_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="space_links",
                        to="properties.motherproperty",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.sourcefile",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="property_links",
                        to="properties.commercialspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mother_property", "space"), name="uniq_property_space"
                    )
                ],
            },
        ),
    ]
