# Generated by Django 5.2.7 on 2026-09-30 07:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("document_type", models.CharField(max_length=80)),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "docx", "xlsx", "png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("sha256", models.CharField(max_length=64)),
                ("content_type", models.CharField(max_length=120)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("entity_type", models.CharField(max_length=80)),
                ("entity_id", models.CharField(max_length=80)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("archived_at", models.DateTimeField(null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
