# Generated by Django 5.2.7 on 2026-09-30 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=120, unique=True)),
                ("persian_label", models.CharField(max_length=255)),
                ("aliases", models.JSONField(default=list)),
                ("data_type", models.CharField(max_length=30)),
                ("domain", models.CharField(max_length=60)),
                ("entity", models.CharField(max_length=60)),
                ("meaning", models.TextField()),
                ("authority", models.CharField(max_length=255)),
                ("precedence", models.PositiveSmallIntegerField(default=1)),
                ("nullable", models.BooleanField(default=True)),
                ("required", models.BooleanField(default=False)),
                ("searchable", models.BooleanField(default=False)),
                ("filterable", models.BooleanField(default=False)),
                ("sortable", models.BooleanField(default=False)),
                ("exportable", models.BooleanField(default=True)),
                ("default_visible", models.BooleanField(default=False)),
                ("sensitive", models.BooleanField(default=False)),
                ("deprecated", models.BooleanField(default=False)),
                ("validation_rules", models.JSONField(default=dict)),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("MAPPED", "Mapped"),
                            ("DERIVED", "Derived"),
                            ("REFERENCE_ONLY", "Reference Only"),
                            ("DEPRECATED", "Deprecated"),
                            ("UNRESOLVED", "Unresolved"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_package", models.CharField(max_length=255)),
                ("package_sha256", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("status", models.CharField(default="RUNNING", max_length=20)),
                ("summary", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="SourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("sha256", models.CharField(max_length=64)),
                ("byte_size", models.PositiveBigIntegerField()),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="registry.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sheet", models.CharField(max_length=255)),
                ("row_number", models.PositiveIntegerField()),
                ("column_number", models.PositiveIntegerField()),
                ("original_heading", models.CharField(max_length=255)),
                ("raw_value", models.TextField(blank=True)),
                ("value_type", models.CharField(max_length=30)),
                ("row_fingerprint", models.CharField(max_length=64)),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("MAPPED", "Mapped"),
                            ("DERIVED", "Derived"),
                            ("REFERENCE_ONLY", "Reference Only"),
                            ("DEPRECATED", "Deprecated"),
                            ("UNRESOLVED", "Unresolved"),
                        ],
                        max_length=20,
                    ),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.canonicalfield",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.sourcefile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discrepancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=80)),
                ("entity_key", models.CharField(max_length=120)),
                ("field_key", models.CharField(blank=True, max_length=120)),
                ("observed_value", models.TextField(blank=True)),
                ("expected_value", models.TextField(blank=True)),
                ("reason", models.TextField()),
                ("severity", models.CharField(default="MEDIUM", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "باز"),
                            ("REVIEWING", "در بررسی"),
                            ("RESOLVED", "حل\u200cشده"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.sourcefile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="sourcefile",
            constraint=models.UniqueConstraint(
                fields=("batch", "filename"), name="uniq_batch_source"
            ),
        ),
        migrations.AddIndex(
            model_name="rawcell",
            index=models.Index(
                fields=["source_file", "sheet", "row_number"],
                name="registry_ra_source__055fb4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rawcell",
            constraint=models.UniqueConstraint(
                fields=("source_file", "sheet", "row_number", "column_number"),
                name="uniq_raw_cell",
            ),
        ),
    ]
