from django.conf import settings
from django.db import models
class Appraisal(models.Model):
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='appraisals'); year=models.CharField(max_length=4,blank=True); sequence=models.CharField(max_length=20,blank=True); amount_rial=models.DecimalField(max_digits=24,decimal_places=0,null=True); appraiser=models.CharField(max_length=255,blank=True); reference=models.CharField(max_length=255,blank=True); appraisal_date=models.CharField(max_length=10,blank=True); status=models.CharField(max_length=80,blank=True); source_file=models.ForeignKey('registry.SourceFile',on_delete=models.PROTECT); source_row=models.PositiveIntegerField()
class AppraisalFee(models.Model):
 appraisal=models.OneToOneField(Appraisal,on_delete=models.PROTECT,related_name='fee'); amount_rial=models.DecimalField(max_digits=24,decimal_places=0); payment_status=models.CharField(max_length=30); payment_date=models.CharField(max_length=10,blank=True); payment_reference=models.CharField(max_length=255,blank=True); follow_up_date=models.CharField(max_length=10,blank=True); notes=models.TextField(blank=True)
class Auction(models.Model):
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='auctions'); year=models.CharField(max_length=4,blank=True); sequence=models.CharField(max_length=20,blank=True); stage=models.CharField(max_length=120,blank=True); result=models.CharField(max_length=120,blank=True); notes=models.TextField(blank=True); source_file=models.ForeignKey('registry.SourceFile',on_delete=models.PROTECT); source_row=models.PositiveIntegerField()
class CommissionDecision(models.Model):
 identity=models.CharField(max_length=120); decision_date=models.CharField(max_length=10); subject=models.CharField(max_length=255); decision=models.TextField(); subsequent_action=models.TextField(blank=True); spaces=models.ManyToManyField('properties.CommercialSpace',related_name='commission_decisions')
class UtilityRecord(models.Model):
 class Type(models.TextChoices): ELECTRICITY='ELECTRICITY','برق'; WATER='WATER','آب'; GAS='GAS','گاز'; OTHER='OTHER','سایر'
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='utilities'); utility_type=models.CharField(max_length=20,choices=Type.choices); account_number=models.CharField(max_length=100); period_start=models.CharField(max_length=10); period_end=models.CharField(max_length=10); consumption=models.DecimalField(max_digits=18,decimal_places=3,null=True); bill_amount_rial=models.DecimalField(max_digits=24,decimal_places=0); organization_share_rial=models.DecimalField(max_digits=24,decimal_places=0); beneficiary_share_rial=models.DecimalField(max_digits=24,decimal_places=0); calculation_basis=models.TextField(); overridden=models.BooleanField(default=False); override_reason=models.TextField(blank=True); payment_status=models.CharField(max_length=30); payment_date=models.CharField(max_length=10,blank=True)
class FileMovement(models.Model):
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='file_movements'); location=models.CharField(max_length=255); holder=models.CharField(max_length=255); delivered_by=models.CharField(max_length=255); received_by=models.CharField(max_length=255); handover_at=models.DateTimeField(); returned_at=models.DateTimeField(null=True); signature_state=models.CharField(max_length=50); direction=models.CharField(max_length=20); next_action=models.CharField(max_length=255,blank=True); due_date=models.CharField(max_length=10,blank=True); notes=models.TextField(blank=True); created_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT)
class TimelineEvent(models.Model):
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='timeline'); event_type=models.CharField(max_length=80); jalali_date=models.CharField(max_length=10,db_index=True); occurred_at=models.DateTimeField(null=True); source_entity=models.CharField(max_length=80); source_entity_id=models.CharField(max_length=80); title=models.CharField(max_length=255); description=models.TextField(blank=True); previous_state=models.CharField(max_length=120,blank=True); new_state=models.CharField(max_length=120,blank=True); responsible_person=models.CharField(max_length=255,blank=True); document=models.ForeignKey('documents.Document',null=True,on_delete=models.PROTECT); provenance=models.TextField(); target_url=models.CharField(max_length=500,blank=True)
class Alert(models.Model):
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='alerts'); subject=models.CharField(max_length=255); reason=models.TextField(); effective_date=models.CharField(max_length=10,blank=True); due_date=models.CharField(max_length=10,blank=True); status=models.CharField(max_length=30); target_url=models.CharField(max_length=500)
