from django.conf import settings
from django.db import models
class Appraisal(models.Model):
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='appraisals'); year=models.CharField(max_length=4,blank=True); sequence=models.CharField(max_length=20,blank=True); amount_rial=models.DecimalField(max_digits=24,decimal_places=0,null=True); appraiser=models.CharField(max_length=255,blank=True); reference=models.CharField(max_length=255,blank=True); appraisal_date=models.CharField(max_length=10,blank=True); status=models.CharField(max_length=80,blank=True); source_file=models.ForeignKey('registry.SourceFile',on_delete=models.PROTECT); source_row=models.PositiveIntegerField()
class AppraisalFee(models.Model):
 appraisal=models.OneToOneField(Appraisal,on_delete=models.PROTECT,related_name='fee'); amount_rial=models.DecimalField(max_digits=24,decimal_places=0); payment_status=models.CharField(max_length=30); payment_date=models.CharField(max_length=10,blank=True); payment_reference=models.CharField(max_length=255,blank=True); follow_up_date=models.CharField(max_length=10,blank=True); notes=models.TextField(blank=True); supporting_document=models.ForeignKey('documents.Document',null=True,blank=True,on_delete=models.PROTECT,related_name='appraisal_fees')
class Auction(models.Model):
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='auctions'); year=models.CharField(max_length=4,blank=True); sequence=models.CharField(max_length=20,blank=True); stage=models.CharField(max_length=120,blank=True); result=models.CharField(max_length=120,blank=True); notes=models.TextField(blank=True); source_file=models.ForeignKey('registry.SourceFile',on_delete=models.PROTECT); source_row=models.PositiveIntegerField()
class AuctionRule(models.Model):
 version=models.CharField(max_length=40,unique=True); effective_year=models.PositiveSmallIntegerField(); contract_window_min_days=models.PositiveSmallIntegerField(default=1); contract_window_max_days=models.PositiveSmallIntegerField(default=90); minor_ceiling_rial=models.DecimalField(max_digits=24,decimal_places=0); medium_ceiling_rial=models.DecimalField(max_digits=24,decimal_places=0); appraisal_valid_months=models.PositiveSmallIntegerField(default=6); active=models.BooleanField(default=False); change_reason=models.TextField(); approved_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT); created_at=models.DateTimeField(auto_now_add=True)
class AuctionEvaluation(models.Model):
 class Decision(models.TextChoices): CANDIDATE='CANDIDATE','کاندیدا'; NOT_CANDIDATE='NOT_CANDIDATE','غیرکاندیدا'; REVIEW_REQUIRED='REVIEW_REQUIRED','نیازمند بررسی'
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='auction_evaluations'); rule=models.ForeignKey(AuctionRule,on_delete=models.PROTECT); decision=models.CharField(max_length=30,choices=Decision.choices); readiness=models.CharField(max_length=30); reason_codes=models.JSONField(); snapshot=models.JSONField(); evaluated_at=models.DateTimeField(auto_now_add=True); evaluated_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT)
class AuctionPeriod(models.Model):
 class State(models.TextChoices): DRAFT='DRAFT','پیش‌نویس'; READY='READY','آماده'; OPENED='OPENED','بازگشایی‌شده'; CLOSED='CLOSED','مختومه'; CANCELLED='CANCELLED','لغوشده'
 identity=models.CharField(max_length=80,unique=True); title=models.CharField(max_length=255); planned_date=models.CharField(max_length=10); state=models.CharField(max_length=20,choices=State.choices,default=State.DRAFT); created_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT); created_at=models.DateTimeField(auto_now_add=True)
class AuctionLot(models.Model):
 period=models.ForeignKey(AuctionPeriod,on_delete=models.PROTECT,related_name='lots'); space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='auction_lots'); evaluation=models.ForeignKey(AuctionEvaluation,on_delete=models.PROTECT); readiness=models.CharField(max_length=30); result=models.CharField(max_length=120,blank=True); winner_name=models.CharField(max_length=255,blank=True); winning_amount_rial=models.DecimalField(max_digits=24,decimal_places=0,null=True); archived=models.BooleanField(default=False)
 class Meta: constraints=[models.UniqueConstraint(fields=['period','space'],name='one_space_per_auction_period')]
class AuctionParticipant(models.Model):
 period=models.ForeignKey(AuctionPeriod,on_delete=models.PROTECT,related_name='participants'); name=models.CharField(max_length=255); identity_number=models.CharField(max_length=30,blank=True); contact=models.CharField(max_length=120,blank=True)
class AuctionProposal(models.Model):
 lot=models.ForeignKey(AuctionLot,on_delete=models.PROTECT,related_name='proposals'); participant=models.ForeignKey(AuctionParticipant,on_delete=models.PROTECT,related_name='proposals'); received_at=models.DateTimeField(); envelope_a_received=models.BooleanField(default=False); envelope_b_received=models.BooleanField(default=False); envelope_c_received=models.BooleanField(default=False); offered_amount_rial=models.DecimalField(max_digits=24,decimal_places=0,null=True); status=models.CharField(max_length=30); document=models.ForeignKey('documents.Document',null=True,blank=True,on_delete=models.PROTECT)
class CommissionDecision(models.Model):
 class State(models.TextChoices): DRAFT='DRAFT','پیش‌نویس'; APPROVED='APPROVED','تصویب‌شده'; CLOSED='CLOSED','مختومه'; CANCELLED='CANCELLED','لغوشده'
 identity=models.CharField(max_length=120); decision_date=models.CharField(max_length=10); subject=models.CharField(max_length=255); decision=models.TextField(); subsequent_action=models.TextField(blank=True); participants=models.TextField(blank=True); state=models.CharField(max_length=20,choices=State.choices,default=State.DRAFT); document=models.ForeignKey('documents.Document',null=True,blank=True,on_delete=models.PROTECT,related_name='commission_decisions'); spaces=models.ManyToManyField('properties.CommercialSpace',related_name='commission_decisions')
class UtilityRecord(models.Model):
 class Type(models.TextChoices): ELECTRICITY='ELECTRICITY','برق'; WATER='WATER','آب'; GAS='GAS','گاز'; OTHER='OTHER','سایر'
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='utilities'); utility_type=models.CharField(max_length=20,choices=Type.choices); account_number=models.CharField(max_length=100); period_start=models.CharField(max_length=10); period_end=models.CharField(max_length=10); consumption=models.DecimalField(max_digits=18,decimal_places=3,null=True); bill_amount_rial=models.DecimalField(max_digits=24,decimal_places=0); organization_share_rial=models.DecimalField(max_digits=24,decimal_places=0); beneficiary_share_rial=models.DecimalField(max_digits=24,decimal_places=0); calculation_basis=models.TextField(); overridden=models.BooleanField(default=False); override_reason=models.TextField(blank=True); payment_status=models.CharField(max_length=30); payment_date=models.CharField(max_length=10,blank=True); supporting_document=models.ForeignKey('documents.Document',null=True,blank=True,on_delete=models.PROTECT,related_name='utility_records')
class FileMovement(models.Model):
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='file_movements'); location=models.CharField(max_length=255); holder=models.CharField(max_length=255); delivered_by=models.CharField(max_length=255); received_by=models.CharField(max_length=255); handover_at=models.DateTimeField(); returned_at=models.DateTimeField(null=True); signature_state=models.CharField(max_length=50); direction=models.CharField(max_length=20); next_action=models.CharField(max_length=255,blank=True); due_date=models.CharField(max_length=10,blank=True); notes=models.TextField(blank=True); created_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT)
class TimelineEvent(models.Model):
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='timeline'); event_type=models.CharField(max_length=80); jalali_date=models.CharField(max_length=10,blank=True,db_index=True); occurred_at=models.DateTimeField(null=True); source_entity=models.CharField(max_length=80); source_entity_id=models.CharField(max_length=80); title=models.CharField(max_length=255); description=models.TextField(blank=True); previous_state=models.CharField(max_length=120,blank=True); new_state=models.CharField(max_length=120,blank=True); responsible_person=models.CharField(max_length=255,blank=True); document=models.ForeignKey('documents.Document',null=True,on_delete=models.PROTECT); provenance=models.TextField(); target_url=models.CharField(max_length=500,blank=True)
 class Meta: ordering=['-jalali_date','-occurred_at','-id']
class Alert(models.Model):
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='alerts'); subject=models.CharField(max_length=255); reason=models.TextField(); effective_date=models.CharField(max_length=10,blank=True); due_date=models.CharField(max_length=10,blank=True); status=models.CharField(max_length=30); target_url=models.CharField(max_length=500)

class DecisionOrder(models.Model):
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='decisions'); decision_type=models.CharField(max_length=120); decision_date=models.CharField(max_length=10,blank=True); letter_number=models.CharField(max_length=120,blank=True); session_reference=models.CharField(max_length=255,blank=True); text=models.TextField(); review_status=models.CharField(max_length=80,blank=True); source_file=models.ForeignKey('registry.SourceFile',on_delete=models.PROTECT); source_row=models.PositiveIntegerField()

class UtilityObligation(models.Model):
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='utility_obligations'); utility_type=models.CharField(max_length=120); calculation_type=models.CharField(max_length=120,blank=True); amount_rial=models.DecimalField(max_digits=24,decimal_places=0,null=True); percentage=models.DecimalField(max_digits=8,decimal_places=3,null=True); standard_description=models.TextField(blank=True); notes=models.TextField(blank=True); source_file=models.ForeignKey('registry.SourceFile',on_delete=models.PROTECT); source_row=models.PositiveIntegerField()

class SourceDocumentReference(models.Model):
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='source_documents'); document_type=models.CharField(max_length=120); reference=models.CharField(max_length=255,blank=True); status=models.CharField(max_length=80,blank=True); source_path=models.TextField(blank=True); notes=models.TextField(blank=True); source_file=models.ForeignKey('registry.SourceFile',on_delete=models.PROTECT); source_row=models.PositiveIntegerField()

class WorkflowInstance(models.Model):
 class State(models.TextChoices): OPEN='OPEN','باز'; DONE='DONE','تکمیل‌شده'; CANCELLED='CANCELLED','لغوشده'
 space=models.ForeignKey('properties.CommercialSpace',on_delete=models.PROTECT,related_name='workflows'); process_type=models.CharField(max_length=80); title=models.CharField(max_length=255); state=models.CharField(max_length=20,choices=State.choices,default=State.OPEN); next_action=models.CharField(max_length=255); due_date=models.CharField(max_length=10,blank=True); created_by=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT); created_at=models.DateTimeField(auto_now_add=True); closed_at=models.DateTimeField(null=True)

class OperationalHistory(models.Model):
 entity_type=models.CharField(max_length=80,db_index=True); entity_id=models.CharField(max_length=80,db_index=True); action=models.CharField(max_length=80); previous_state=models.JSONField(null=True); new_state=models.JSONField(null=True); reason=models.TextField(blank=True); responsible=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT); occurred_at=models.DateTimeField(auto_now_add=True)
 class Meta: ordering=['-occurred_at','-id']
