# Generated for SAMA utilities module.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0001_initial"),
    ]
    operations = [
        migrations.CreateModel(
            name="UtilityAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("utility_type", models.CharField(choices=[("ELECTRICITY", "برق"), ("WATER", "آب"), ("GAS", "گاز"), ("TELEPHONE", "تلفن"), ("OTHER", "سایر")], db_index=True, max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("account_number", models.CharField(blank=True, db_index=True, max_length=120)),
                ("bill_identifier", models.CharField(blank=True, db_index=True, max_length=120)),
                ("payment_identifier", models.CharField(blank=True, max_length=120)),
                ("meter_number", models.CharField(blank=True, db_index=True, max_length=120)),
                ("ownership", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(choices=[("ACTIVE", "فعال"), ("DISCONNECTED", "قطع"), ("INACTIVE", "غیرفعال"), ("TRANSFER", "در حال انتقال"), ("REVIEW", "نیازمند بررسی")], db_index=True, default="ACTIVE", max_length=20)),
                ("technical_capacity", models.CharField(blank=True, max_length=255)),
                ("service_address", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("center", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="utility_accounts", to="properties.center")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_utility_accounts", to=settings.AUTH_USER_MODEL)),
                ("dedicated_space", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="dedicated_utility_accounts", to="properties.commercialspace")),
                ("mother_property", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="utility_accounts", to="properties.motherproperty")),
                ("region", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="utility_accounts", to="properties.region")),
            ],
            options={"ordering": ["utility_type", "title", "id"]},
        ),
        migrations.AddConstraint(
            model_name="utilityaccount",
            constraint=models.UniqueConstraint(condition=models.Q(("account_number", ""), _negated=True), fields=("utility_type", "account_number"), name="uniq_utility_type_account_number"),
        ),
        migrations.CreateModel(
            name="UtilityAllocationPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("method", models.CharField(choices=[("METHOD3", "روش سوم — ترکیبی نهایی")], default="METHOD3", max_length=20)),
                ("beneficiary_percent", models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ("organization_percent", models.DecimalField(decimal_places=4, default=100, max_digits=7)),
                ("season_factor", models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ("editable", models.BooleanField(default=True)),
                ("approved_reference", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="allocation_policy", to="utilities.utilityaccount")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="updated_utility_policies", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="UtilitySpaceProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("included", models.BooleanField(default=True)),
                ("consumption_category", models.CharField(blank=True, max_length=255)),
                ("special_model", models.CharField(choices=[("NORMAL", "عادی"), ("EQUIPMENT", "تجهیزات‌محور"), ("OPEN_AREA", "فضای باز"), ("LIGHTING", "روشنایی محوطه"), ("WATER_FEATURE", "محوطه آبی"), ("OTHER", "سایر")], default="NORMAL", max_length=20)),
                ("area_override", models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ("eui", models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ("hours_factor", models.DecimalField(decimal_places=6, default=1, max_digits=16)),
                ("category_factor", models.DecimalField(decimal_places=6, default=1, max_digits=16)),
                ("row_factor", models.DecimalField(decimal_places=6, default=1, max_digits=16)),
                ("special_consumption", models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ("manual_share_percent", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("manual_share_locked", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="space_profiles", to="utilities.utilityaccount")),
                ("space", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="utility_profiles", to="properties.commercialspace")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="updated_utility_profiles", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["space__code"]},
        ),
        migrations.AddConstraint(
            model_name="utilityspaceprofile",
            constraint=models.UniqueConstraint(fields=("account", "space"), name="uniq_utility_account_space_profile"),
        ),
        migrations.CreateModel(
            name="UtilityBill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.CharField(blank=True, db_index=True, max_length=10)),
                ("period_end", models.CharField(blank=True, db_index=True, max_length=10)),
                ("bill_date", models.CharField(blank=True, max_length=10)),
                ("due_date", models.CharField(blank=True, db_index=True, max_length=10)),
                ("total_consumption", models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ("amount_rial", models.DecimalField(decimal_places=0, max_digits=24)),
                ("status", models.CharField(choices=[("DRAFT", "پیش‌نویس"), ("CALCULATED", "محاسبه‌شده"), ("PARTIAL", "پرداخت ناقص"), ("PAID", "پرداخت‌شده"), ("OVERDUE", "سررسیدگذشته"), ("CANCELLED", "لغوشده")], db_index=True, default="DRAFT", max_length=20)),
                ("organization_percent_effective", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("beneficiary_percent_effective", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("organization_amount_rial", models.DecimalField(blank=True, decimal_places=0, max_digits=24, null=True)),
                ("beneficiary_amount_rial", models.DecimalField(blank=True, decimal_places=0, max_digits=24, null=True)),
                ("calculation_snapshot", models.JSONField(blank=True, default=dict)),
                ("attachment", models.FileField(blank=True, upload_to="utilities/bills/%Y/%m/")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bills", to="utilities.utilityaccount")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_utility_bills", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-period_end", "-id"]},
        ),
        migrations.CreateModel(
            name="UtilityMeterReading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("measured_consumption", models.DecimalField(decimal_places=6, max_digits=24)),
                ("reading_date", models.CharField(blank=True, max_length=10)),
                ("meter_number", models.CharField(blank=True, max_length=120)),
                ("is_valid", models.BooleanField(default=True)),
                ("source_note", models.TextField(blank=True)),
                ("bill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="meter_readings", to="utilities.utilitybill")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="meter_readings", to="utilities.utilityspaceprofile")),
            ],
        ),
        migrations.AddConstraint(
            model_name="utilitymeterreading",
            constraint=models.UniqueConstraint(fields=("bill", "profile"), name="uniq_bill_profile_meter_reading"),
        ),
        migrations.CreateModel(
            name="UtilityAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("basis", models.CharField(choices=[("MEASURED", "زیرکنتور / اندازه‌گیری واقعی"), ("EQUIPMENT", "مصرف ویژه تجهیزات"), ("METHOD3", "روش سوم"), ("MANUAL", "درصد دستی قفل‌شده")], max_length=20)),
                ("consumption_weight", models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ("share_percent", models.DecimalField(decimal_places=8, max_digits=12)),
                ("amount_rial", models.DecimalField(decimal_places=0, max_digits=24)),
                ("overridden", models.BooleanField(default=False)),
                ("override_reason", models.TextField(blank=True)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bill", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="allocations", to="utilities.utilitybill")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="allocations", to="utilities.utilityspaceprofile")),
            ],
            options={"ordering": ["-share_percent", "id"]},
        ),
        migrations.AddConstraint(
            model_name="utilityallocation",
            constraint=models.UniqueConstraint(fields=("bill", "profile"), name="uniq_bill_profile_allocation"),
        ),
        migrations.CreateModel(
            name="UtilityPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payer", models.CharField(choices=[("ORGANIZATION", "سازمان"), ("BENEFICIARY", "بهره‌بردار"), ("MIXED", "مشترک")], max_length=20)),
                ("amount_rial", models.DecimalField(decimal_places=0, max_digits=24)),
                ("payment_date", models.CharField(max_length=10)),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("attachment", models.FileField(blank=True, upload_to="utilities/payments/%Y/%m/")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("allocation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="utilities.utilityallocation")),
                ("bill", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="utilities.utilitybill")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_utility_payments", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="UtilityChangeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entity_type", models.CharField(db_index=True, max_length=80)),
                ("entity_id", models.CharField(db_index=True, max_length=80)),
                ("action", models.CharField(max_length=80)),
                ("previous_state", models.JSONField(blank=True, null=True)),
                ("new_state", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("responsible", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="utility_change_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-occurred_at", "-id"]},
        ),
    ]
