# Generated by Django 5.2.7 on 2026-09-30 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("properties", "0001_initial"),
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("reason", models.TextField()),
                ("effective_date", models.CharField(blank=True, max_length=10)),
                ("due_date", models.CharField(blank=True, max_length=10)),
                ("status", models.CharField(max_length=30)),
                ("target_url", models.CharField(max_length=500)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alerts",
                        to="properties.commercialspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appraisal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(blank=True, max_length=4)),
                ("sequence", models.CharField(blank=True, max_length=20)),
                (
                    "amount_rial",
                    models.DecimalField(decimal_places=0, max_digits=24, null=True),
                ),
                ("appraiser", models.CharField(blank=True, max_length=255)),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("appraisal_date", models.CharField(blank=True, max_length=10)),
                ("status", models.CharField(blank=True, max_length=80)),
                ("source_row", models.PositiveIntegerField()),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.sourcefile",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appraisals",
                        to="properties.commercialspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppraisalFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_rial", models.DecimalField(decimal_places=0, max_digits=24)),
                ("payment_status", models.CharField(max_length=30)),
                ("payment_date", models.CharField(blank=True, max_length=10)),
                ("payment_reference", models.CharField(blank=True, max_length=255)),
                ("follow_up_date", models.CharField(blank=True, max_length=10)),
                ("notes", models.TextField(blank=True)),
                (
                    "appraisal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee",
                        to="operations.appraisal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(blank=True, max_length=4)),
                ("sequence", models.CharField(blank=True, max_length=20)),
                ("stage", models.CharField(blank=True, max_length=120)),
                ("result", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("source_row", models.PositiveIntegerField()),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.sourcefile",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auctions",
                        to="properties.commercialspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommissionDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identity", models.CharField(max_length=120)),
                ("decision_date", models.CharField(max_length=10)),
                ("subject", models.CharField(max_length=255)),
                ("decision", models.TextField()),
                ("subsequent_action", models.TextField(blank=True)),
                (
                    "spaces",
                    models.ManyToManyField(
                        related_name="commission_decisions",
                        to="properties.commercialspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("holder", models.CharField(max_length=255)),
                ("delivered_by", models.CharField(max_length=255)),
                ("received_by", models.CharField(max_length=255)),
                ("handover_at", models.DateTimeField()),
                ("returned_at", models.DateTimeField(null=True)),
                ("signature_state", models.CharField(max_length=50)),
                ("direction", models.CharField(max_length=20)),
                ("next_action", models.CharField(blank=True, max_length=255)),
                ("due_date", models.CharField(blank=True, max_length=10)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_movements",
                        to="properties.commercialspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=80)),
                ("jalali_date", models.CharField(db_index=True, max_length=10)),
                ("occurred_at", models.DateTimeField(null=True)),
                ("source_entity", models.CharField(max_length=80)),
                ("source_entity_id", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("previous_state", models.CharField(blank=True, max_length=120)),
                ("new_state", models.CharField(blank=True, max_length=120)),
                ("responsible_person", models.CharField(blank=True, max_length=255)),
                ("provenance", models.TextField()),
                ("target_url", models.CharField(blank=True, max_length=500)),
                (
                    "document",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.document",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline",
                        to="properties.commercialspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UtilityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "utility_type",
                    models.CharField(
                        choices=[
                            ("ELECTRICITY", "برق"),
                            ("WATER", "آب"),
                            ("GAS", "گاز"),
                            ("OTHER", "سایر"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_number", models.CharField(max_length=100)),
                ("period_start", models.CharField(max_length=10)),
                ("period_end", models.CharField(max_length=10)),
                (
                    "consumption",
                    models.DecimalField(decimal_places=3, max_digits=18, null=True),
                ),
                (
                    "bill_amount_rial",
                    models.DecimalField(decimal_places=0, max_digits=24),
                ),
                (
                    "organization_share_rial",
                    models.DecimalField(decimal_places=0, max_digits=24),
                ),
                (
                    "beneficiary_share_rial",
                    models.DecimalField(decimal_places=0, max_digits=24),
                ),
                ("calculation_basis", models.TextField()),
                ("overridden", models.BooleanField(default=False)),
                ("override_reason", models.TextField(blank=True)),
                ("payment_status", models.CharField(max_length=30)),
                ("payment_date", models.CharField(blank=True, max_length=10)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utilities",
                        to="properties.commercialspace",
                    ),
                ),
            ],
        ),
    ]
