# Generated by Django 5.2.7 on 2026-09-30 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
        ("properties", "0001_initial"),
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decision_type", models.CharField(max_length=120)),
                ("decision_date", models.CharField(blank=True, max_length=10)),
                ("letter_number", models.CharField(blank=True, max_length=120)),
                ("session_reference", models.CharField(blank=True, max_length=255)),
                ("text", models.TextField()),
                ("review_status", models.CharField(blank=True, max_length=80)),
                ("source_row", models.PositiveIntegerField()),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.sourcefile",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="properties.commercialspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceDocumentReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=120)),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(blank=True, max_length=80)),
                ("source_path", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("source_row", models.PositiveIntegerField()),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.sourcefile",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_documents",
                        to="properties.commercialspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UtilityObligation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("utility_type", models.CharField(max_length=120)),
                ("calculation_type", models.CharField(blank=True, max_length=120)),
                (
                    "amount_rial",
                    models.DecimalField(decimal_places=0, max_digits=24, null=True),
                ),
                (
                    "percentage",
                    models.DecimalField(decimal_places=3, max_digits=8, null=True),
                ),
                ("standard_description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("source_row", models.PositiveIntegerField()),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.sourcefile",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utility_obligations",
                        to="properties.commercialspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("process_type", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("OPEN", "باز"),
                            ("DONE", "تکمیل\u200cشده"),
                            ("CANCELLED", "لغوشده"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("next_action", models.CharField(max_length=255)),
                ("due_date", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflows",
                        to="properties.commercialspace",
                    ),
                ),
            ],
        ),
    ]
