# Generated by Django 5.2.7 on 2026-09-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_decisionorder_sourcedocumentreference_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timelineevent",
            options={"ordering": ["-jalali_date", "-occurred_at", "-id"]},
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="jalali_date",
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
