# Generated by Django 5.2.7 on 2026-09-30 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("operations", "0003_alter_timelineevent_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appraisalfee",
            name="supporting_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appraisal_fees",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="commissiondecision",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commission_decisions",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="commissiondecision",
            name="participants",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="commissiondecision",
            name="state",
            field=models.CharField(
                choices=[
                    ("DRAFT", "پیش\u200cنویس"),
                    ("APPROVED", "تصویب\u200cشده"),
                    ("CLOSED", "مختومه"),
                    ("CANCELLED", "لغوشده"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="utilityrecord",
            name="supporting_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="utility_records",
                to="documents.document",
            ),
        ),
        migrations.CreateModel(
            name="OperationalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=80)),
                ("entity_id", models.CharField(db_index=True, max_length=80)),
                ("action", models.CharField(max_length=80)),
                ("previous_state", models.JSONField(null=True)),
                ("new_state", models.JSONField(null=True)),
                ("reason", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
    ]
