# Generated by Django 5.2.7 on 2026-09-30 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("operations", "0004_appraisalfee_supporting_document_and_more"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("CANDIDATE", "کاندیدا"),
                            ("NOT_CANDIDATE", "غیرکاندیدا"),
                            ("REVIEW_REQUIRED", "نیازمند بررسی"),
                        ],
                        max_length=30,
                    ),
                ),
                ("readiness", models.CharField(max_length=30)),
                ("reason_codes", models.JSONField()),
                ("snapshot", models.JSONField()),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auction_evaluations",
                        to="properties.commercialspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuctionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identity", models.CharField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("planned_date", models.CharField(max_length=10)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "پیش\u200cنویس"),
                            ("READY", "آماده"),
                            ("OPENED", "بازگشایی\u200cشده"),
                            ("CLOSED", "مختومه"),
                            ("CANCELLED", "لغوشده"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuctionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("identity_number", models.CharField(blank=True, max_length=30)),
                ("contact", models.CharField(blank=True, max_length=120)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participants",
                        to="operations.auctionperiod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuctionLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("readiness", models.CharField(max_length=30)),
                ("result", models.CharField(blank=True, max_length=120)),
                ("winner_name", models.CharField(blank=True, max_length=255)),
                (
                    "winning_amount_rial",
                    models.DecimalField(decimal_places=0, max_digits=24, null=True),
                ),
                ("archived", models.BooleanField(default=False)),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.auctionevaluation",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auction_lots",
                        to="properties.commercialspace",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="operations.auctionperiod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuctionProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_at", models.DateTimeField()),
                ("envelope_a_received", models.BooleanField(default=False)),
                ("envelope_b_received", models.BooleanField(default=False)),
                ("envelope_c_received", models.BooleanField(default=False)),
                (
                    "offered_amount_rial",
                    models.DecimalField(decimal_places=0, max_digits=24, null=True),
                ),
                ("status", models.CharField(max_length=30)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.document",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals",
                        to="operations.auctionlot",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals",
                        to="operations.auctionparticipant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuctionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=40, unique=True)),
                ("effective_year", models.PositiveSmallIntegerField()),
                (
                    "contract_window_min_days",
                    models.PositiveSmallIntegerField(default=1),
                ),
                (
                    "contract_window_max_days",
                    models.PositiveSmallIntegerField(default=90),
                ),
                (
                    "minor_ceiling_rial",
                    models.DecimalField(decimal_places=0, max_digits=24),
                ),
                (
                    "medium_ceiling_rial",
                    models.DecimalField(decimal_places=0, max_digits=24),
                ),
                ("appraisal_valid_months", models.PositiveSmallIntegerField(default=6)),
                ("active", models.BooleanField(default=False)),
                ("change_reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="auctionevaluation",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="operations.auctionrule"
            ),
        ),
        migrations.AddConstraint(
            model_name="auctionlot",
            constraint=models.UniqueConstraint(
                fields=("period", "space"), name="one_space_per_auction_period"
            ),
        ),
    ]
