# Generated by Django 5.2.7 on 2026-10-01 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0006_appraisal_created_at_appraisal_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "کم"),
                    ("MEDIUM", "متوسط"),
                    ("HIGH", "زیاد"),
                    ("CRITICAL", "بحرانی"),
                ],
                default="MEDIUM",
                max_length=20,
            ),
        ),
    ]
