# Generated by Django 5.2.7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contracts', '0004_contract_circulation'),
        ('documents', '0001_initial'),
        ('operations', '0007_alert_actionability'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('CHAIR', 'رئیس'), ('SECRETARY', 'دبیر'), ('MEMBER', 'عضو'), ('OBSERVER', 'ناظر / مدعو')], default='MEMBER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('signature_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('membership_start', models.CharField(blank=True, max_length=10)),
                ('membership_end', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={'ordering': ['signature_order', 'full_name']},
        ),
        migrations.CreateModel(
            name='CommissionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('session_number', models.CharField(blank=True, max_length=120)),
                ('session_date', models.CharField(db_index=True, max_length=10)),
                ('session_time', models.CharField(blank=True, max_length=5)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('DRAFT', 'پیش‌نویس'), ('PLANNED', 'برنامه‌ریزی‌شده'), ('HELD', 'برگزارشده'), ('FINALIZED', 'نهایی‌شده'), ('CANCELLED', 'لغوشده')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_sessions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-session_date', '-id']},
        ),
        migrations.CreateModel(
            name='CommissionSessionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=80)),
                ('attendance', models.CharField(choices=[('PRESENT', 'حاضر'), ('ABSENT', 'غایب'), ('EXCUSED', 'غایب موجه')], default='PRESENT', max_length=20)),
                ('signature_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_snapshots', to='commission.commissionmember')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_members', to='commission.commissionsession')),
            ],
            options={'ordering': ['signature_order', 'id']},
        ),
        migrations.CreateModel(
            name='CommissionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('referral_reason', models.TextField()),
                ('case_type', models.CharField(max_length=120)),
                ('referral_source', models.CharField(blank=True, max_length=255)),
                ('review_state', models.CharField(choices=[('DRAFT', 'پیش‌نویس'), ('ON_AGENDA', 'در دستور جلسه'), ('REVIEWED', 'بررسی‌شده'), ('DEFERRED', 'موکول‌شده'), ('CLOSED', 'مختومه')], db_index=True, default='ON_AGENDA', max_length=20)),
                ('result_summary', models.TextField(blank=True)),
                ('follow_up_owner', models.CharField(blank=True, max_length=255)),
                ('execution_state', models.CharField(choices=[('NOT_REQUIRED', 'نیازمند اجرا نیست'), ('PENDING', 'در انتظار اجرا'), ('IN_PROGRESS', 'در حال اجرا'), ('DONE', 'انجام‌شده'), ('OVERDUE', 'سررسید گذشته')], db_index=True, default='NOT_REQUIRED', max_length=20)),
                ('follow_up_deadline', models.CharField(blank=True, db_index=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_cases_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='commission.commissionsession')),
            ],
            options={'ordering': ['session_id', 'id']},
        ),
        migrations.CreateModel(
            name='CommissionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(blank=True, editable=False, max_length=32, unique=True)),
                ('decision_date', models.CharField(db_index=True, max_length=10)),
                ('decision_type', models.CharField(max_length=120)),
                ('formal_text', models.TextField()),
                ('result', models.CharField(blank=True, max_length=255)),
                ('execution_owner', models.CharField(blank=True, max_length=255)),
                ('execution_deadline', models.CharField(blank=True, db_index=True, max_length=10)),
                ('execution_state', models.CharField(choices=[('PENDING', 'در انتظار اجرا'), ('IN_PROGRESS', 'در حال اجرا'), ('DONE', 'انجام‌شده'), ('CANCELLED', 'لغوشده')], db_index=True, default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='commission.commissioncase')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_decisions_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_formal_decisions', to='documents.document')),
            ],
            options={'ordering': ['-decision_date', '-id']},
        ),
        migrations.CreateModel(
            name='CommissionFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('owner', models.CharField(max_length=255)),
                ('due_date', models.CharField(blank=True, db_index=True, max_length=10)),
                ('state', models.CharField(choices=[('OPEN', 'باز'), ('IN_PROGRESS', 'در حال پیگیری'), ('DONE', 'انجام‌شده'), ('CANCELLED', 'لغوشده')], db_index=True, default='OPEN', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_followups_created', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='commission.commissiondecision')),
            ],
            options={'ordering': ['state', 'due_date', 'id']},
        ),
        migrations.CreateModel(
            name='CommissionRelatedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('auction_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_cases', to='operations.auctionperiod')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_cases', to='contracts.beneficiary')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_entities', to='commission.commissioncase')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_cases', to='contracts.contract')),
                ('mother_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_cases', to='properties.motherproperty')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_cases', to='properties.commercialspace')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionSessionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_role', models.CharField(default='صورتجلسه', max_length=120)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_sessions', to='documents.document')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_documents', to='commission.commissionsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='commissionsessionmember',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('session', 'member'), name='unique_reference_member_per_commission_session'),
        ),
        migrations.AddConstraint(
            model_name='commissionrelatedentity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('auction_period__isnull', True), ('beneficiary__isnull', True), ('contract__isnull', True), ('mother_property__isnull', True), ('space__isnull', False)), models.Q(('auction_period__isnull', True), ('beneficiary__isnull', True), ('contract__isnull', False), ('mother_property__isnull', True), ('space__isnull', True)), models.Q(('auction_period__isnull', True), ('beneficiary__isnull', False), ('contract__isnull', True), ('mother_property__isnull', True), ('space__isnull', True)), models.Q(('auction_period__isnull', False), ('beneficiary__isnull', True), ('contract__isnull', True), ('mother_property__isnull', True), ('space__isnull', True)), models.Q(('auction_period__isnull', True), ('beneficiary__isnull', True), ('contract__isnull', True), ('mother_property__isnull', False), ('space__isnull', True)), _connector='OR'), name='commission_related_entity_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='commissionsessiondocument',
            constraint=models.UniqueConstraint(fields=('session', 'document'), name='unique_document_per_commission_session'),
        ),
    ]
