# Generated by Django 5.2.7 on 2026-09-30 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("identity_number", models.CharField(blank=True, max_length=30)),
                ("kind", models.CharField(default="PERSON", max_length=30)),
                ("contact", models.CharField(blank=True, max_length=255)),
                ("archived_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BeneficiaryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=120)),
                ("start_date", models.CharField(blank=True, max_length=10)),
                ("end_date", models.CharField(blank=True, max_length=10)),
                ("status", models.CharField(max_length=40)),
                ("source_row", models.PositiveIntegerField()),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.beneficiary",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.sourcefile",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiary_assignments",
                        to="properties.commercialspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, db_index=True, max_length=120)),
                ("signed_date", models.CharField(blank=True, max_length=10)),
                ("start_date", models.CharField(blank=True, max_length=10)),
                ("end_date", models.CharField(blank=True, max_length=10)),
                (
                    "amount_rial",
                    models.DecimalField(decimal_places=0, max_digits=24, null=True),
                ),
                (
                    "investment_commitment_rial",
                    models.DecimalField(decimal_places=0, max_digits=24, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=80)),
                ("signed_state", models.CharField(blank=True, max_length=80)),
                ("is_historical", models.BooleanField(default=True)),
                ("source_row", models.PositiveIntegerField()),
                (
                    "beneficiary",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contracts.beneficiary",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.sourcefile",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="properties.commercialspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=120)),
                ("effective_date", models.CharField(max_length=10)),
                ("description", models.TextField()),
                (
                    "amount_change_rial",
                    models.DecimalField(decimal_places=0, max_digits=24, null=True),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amendments",
                        to="contracts.contract",
                    ),
                ),
            ],
        ),
    ]
