# Generated by Django 5.2.7 on 2026-10-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_beneficiaryassignment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiary",
            name="kind",
            field=models.CharField(
                choices=[
                    ("NATURAL", "شخص حقیقی"),
                    ("LEGAL", "شخص حقوقی"),
                    ("TRADE_NAME", "نام تجاری"),
                    ("UNSPECIFIED", "نوع نامشخص در منبع"),
                ],
                default="UNSPECIFIED",
                max_length=30,
            ),
        ),
    ]
