from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('contracts','0003_beneficiary_kind_choices'),('properties','0001_initial'),('documents','0001_initial'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='ContractCirculation',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('identity',models.CharField(blank=True,editable=False,max_length=30,unique=True)),('subject',models.CharField(max_length=255)),('operational_start_date',models.CharField(default='1405/07/01',max_length=10)),('state',models.CharField(choices=[('RECEIVED','دریافت‌شده'),('READY','آماده ارسال'),('SIGNING','در گردش امضا'),('RETURNED','برگشت برای اصلاح'),('RESEND','ارسال مجدد'),('READY_APPROVAL','آماده تأیید نهایی'),('APPROVED','تأیید نهایی‌شده'),('CONVERTED','تبدیل‌شده به قرارداد رسمی'),('CLOSED_NO_CONTRACT','مختومه بدون قرارداد')],default='RECEIVED',max_length=30)),('next_action',models.CharField(max_length=255)),('due_date',models.CharField(blank=True,max_length=10)),('created_at',models.DateTimeField(auto_now_add=True)),('beneficiary',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='contract_circulations',to='contracts.beneficiary')),('created_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='created_contract_circulations',to=settings.AUTH_USER_MODEL)),('official_contract',models.OneToOneField(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='source_circulation',to='contracts.contract')),('space',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='contract_circulations',to='properties.commercialspace'))],options={'indexes':[models.Index(fields=['state','due_date'],name='contracts_c_state_3eeafe_idx')]}),
  migrations.CreateModel(name='ContractCustodyTransfer',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('sender',models.CharField(max_length=255)),('receiver',models.CharField(max_length=255)),('unit',models.CharField(max_length=255)),('delivered_at',models.DateTimeField()),('purpose',models.CharField(max_length=255)),('next_action',models.CharField(max_length=255)),('due_date',models.CharField(blank=True,max_length=10)),('direction',models.CharField(default='OUT',max_length=20)),('signature_status',models.CharField(blank=True,max_length=80)),('returned_at',models.DateTimeField(blank=True,null=True)),('return_note',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('circulation',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='transfers',to='contracts.contractcirculation')),('created_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL)),('document',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,to='documents.document'))],options={'ordering':['-delivered_at','-id'],'constraints':[models.UniqueConstraint(condition=models.Q(('returned_at__isnull',True)),fields=('circulation',),name='one_open_contract_custody')]}),
  migrations.CreateModel(name='ContractSignatureStep',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('order',models.PositiveSmallIntegerField()),('role',models.CharField(max_length=120)),('person',models.CharField(blank=True,max_length=255)),('unit',models.CharField(max_length=255)),('required',models.BooleanField(default=True)),('sent_at',models.DateTimeField(blank=True,null=True)),('signed_at',models.DateTimeField(blank=True,null=True)),('returned_at',models.DateTimeField(blank=True,null=True)),('status',models.CharField(choices=[('PENDING','در انتظار ارسال'),('SENT','ارسال‌شده برای امضا'),('SIGNED','امضاشده'),('RETURNED','برگشت برای اصلاح'),('WAIVED','صرف‌نظر از مرحله اختیاری')],default='PENDING',max_length=20)),('note',models.TextField(blank=True)),('updated_at',models.DateTimeField(auto_now=True)),('circulation',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='signature_steps',to='contracts.contractcirculation')),('document',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,to='documents.document')),('updated_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL))],options={'ordering':['order','id'],'constraints':[models.UniqueConstraint(fields=('circulation','order'),name='unique_signature_order')]}),
  migrations.CreateModel(name='ContractFinalApproval',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('approved_at',models.DateTimeField()),('note',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('approver',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL)),('circulation',models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name='final_approval',to='contracts.contractcirculation'))]),
 ]
